type_choices = (
        ('Science fiction', 'Science fiction'),
        ('Satire', 'Satire'),
        ('Action and Adventure', 'Action and Adventure'),
        ('Romance', 'Romance'),
        ('Mystery', 'Mystery'),
        ('Horror', 'Horror'),
        ('Health', 'Health'),
        ('Guide', 'Guide'),
        ('Childrens', 'Childrens'),
        ('Religion, Spirituality & New Age', 'Religion, Spirituality & New Age'),
        ('Science', 'Science'),
        ('History', 'History'),
        ('Math', 'Math'),
        ('Poetry', 'Poetry'),
        ('Encyclopedias', 'Encyclopedias'),
        ('Dictionaries', 'Dictionaries'),
        ('Comics', 'Comics'),
        ('Art', 'Art'),
        ('Cook', 'Cook'),
        ('Diaries', 'Diaries'),
        ('Journals', 'Journals'),
        ('Trilogy', 'Trilogy'),
        ('Biographies', 'Biographies'),
        ('Fantasy', 'Fantasy'),
        ('Others', 'Others'),
    )